"""Crear tablas iniciales

Revision ID: c3a847cee7f6
Revises: 
Create Date: 2025-02-05 11:48:28.305562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a847cee7f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('representante', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.SmallInteger(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_reunion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.SmallInteger(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('identificacion', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.SmallInteger(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('reuniones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('lugar', sa.String(length=200), nullable=False),
    sa.Column('tipo_reunion_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.SmallInteger(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.ForeignKeyConstraint(['tipo_reunion_id'], ['tipos_reunion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reunion_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('asistio', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.SmallInteger(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['reunion_id'], ['reuniones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asistencias')
    op.drop_table('reuniones')
    op.drop_table('clientes')
    op.drop_table('tipos_reunion')
    op.drop_table('organizaciones')
    # ### end Alembic commands ###
